version: "2.2"
services:
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter-notebook
    volumes:
      - /srv/jupyter:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 9999:8888
    restart: unless-stopped
