version: "2.2"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 8000:8000
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
